/** All limits and constraints. PRD various sections. */

export const LIMITS = {
  // Timer (Section 6.1)
  FOCUS_MIN: 1,
  FOCUS_MAX: 120,
  SHORT_BREAK_MIN: 1,
  SHORT_BREAK_MAX: 30,
  LONG_BREAK_MIN: 1,
  LONG_BREAK_MAX: 60,
  CYCLE_MIN: 2,
  CYCLE_MAX: 10,
  MIN_COUNTABLE_MIN: 1,
  MIN_COUNTABLE_MAX: 25,
  DAILY_GOAL_MIN: 1,
  DAILY_GOAL_MAX: 20,
  WEEKLY_GOAL_MIN: 5,
  WEEKLY_GOAL_MAX: 100,
  STREAK_FREEZE_MIN: 0,
  STREAK_FREEZE_MAX: 8,

  // Input lengths
  INTENT_MAX_LENGTH: 120,
  INTENT_WARNING_THRESHOLD: 80,
  INTENT_DANGER_THRESHOLD: 115,
  CATEGORY_NAME_MAX_LENGTH: 24,
  MAX_CATEGORIES: 20,
  FEEDBACK_SUBJECT_MAX_LENGTH: 100,
  FEEDBACK_DESCRIPTION_MAX_LENGTH: 2000,
  FEEDBACK_DESCRIPTION_MIN_LENGTH: 10,
  SESSION_NOTES_MAX_LENGTH: 500,
  CUSTOM_SOUND_MAX_SIZE_BYTES: 500 * 1024,
  CUSTOM_SOUND_MAX_DURATION_SECONDS: 5,
  MAX_SCREENSHOT_FILES: 3,
  MAX_SCREENSHOT_SIZE_BYTES: 5 * 1024 * 1024,

  // Rate limiting
  LOGIN_RATE_LIMIT_PER_MINUTE: 10,
  ADMIN_API_RATE_LIMIT_PER_MINUTE: 60,
  GENERAL_API_RATE_LIMIT_PER_MINUTE: 100,

  // Pagination
  SESSION_LOG_INITIAL_PAGE_SIZE: 50,
  SESSION_LOG_LOAD_MORE_SIZE: 25,
  ADMIN_FEEDBACK_LIMIT: 50,

  // Sync intervals (ms)
  SETTINGS_DEBOUNCE_MS: 500,
  TIMER_HEARTBEAT_INTERVAL_MS: 15_000,
  TIMER_HEARTBEAT_TIMEOUT_MS: 60_000,
  DASHBOARD_POLL_INTERVAL_MS: 30_000,
  ADMIN_PULSE_INTERVAL_MS: 10_000,
  SETTINGS_SYNC_INTERVAL_MS: 5_000,
  FOOTER_STATS_POLL_INTERVAL_MS: 30_000,

  // Session
  SESSION_COOKIE_MAX_AGE_DAYS: 30,
  SOFT_DELETE_RETENTION_DAYS: 30,

  // Autocomplete
  AUTOCOMPLETE_MIN_CHARS: 2,
  AUTOCOMPLETE_MAX_RESULTS: 5,
} as const;
